Name: greet.rpc
ListenOn: 0.0.0.0:8080
Mode: dev
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: greet.rpc

Gateway:
  Name: greet.api
  Host: localhost
  Port: 8888
  Upstreams:
  - Grpc:
      Target: 0.0.0.0:8080
      # Mappings can also be written in proto options
    Mappings:
      - Method: get
        Path: /ping
        RpcPath: greet.Greet/Ping
