server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(192.168.199.237:3306)/test
  redis:
    addr: 192.168.199.237:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
naming:
  etcd:
    addr: 
      - 192.168.199.237:2379
    # username: ""
    # password: ""
    # timeout: 30
