Name: order.rpc
ListenOn: 0.0.0.0:8888
Mode: dev
DevServer: 
  Enable: true
# Log:
#   Mode: volume
#   Path: /var/logs
#   KeepDays: 2
#   Rotation: size
#   MaxSize: 25
#   MaxBackups: 30

Gateway:
  Name: order.api
  # Host: localhost
  Port: 9999
  Upstreams:
  - Grpc:
      Target: 0.0.0.0:8888
      # Mappings can also be written in proto options
    Mappings:
      - Method: get
        Path: /ping
        RpcPath: order.Order/Ping
