Name: order.rpc
ListenOn: 0.0.0.0:8888
Mode: dev
DevServer: 
  Enable: true
# Log:
#   Mode: volume
#   Path: /var/logs
#   KeepDays: 1
#   Rotation: size
#   MaxSize: 20
#   MaxBackups: 20

LoggerKafkaQueue:
  Brokers: 
    - "kafka.ops:9092"
  Topic: "k8s.log"

Gateway:
  Name: order.api
  # Host: localhost
  Port: 9999
  Upstreams:
  - Grpc:
      Target: 0.0.0.0:8888
      # Mappings can also be written in proto options
    ProtoSets: 
    - ./gateway/annotations.pb
    - ./gateway/http.pb
    - ./gateway/descriptor.pb
    - ./gateway/greet.proto.pb

