// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"learn-k8s/app/getway/service/internal/biz"
	"learn-k8s/app/getway/service/internal/conf"
	"learn-k8s/app/getway/service/internal/data"
	"learn-k8s/app/getway/service/internal/server"
	"learn-k8s/app/getway/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, naming *conf.Naming, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(naming)
	goodsClient := biz.NewGoodsServiceClient(discovery, logger)
	userClient := biz.NewUserServiceClient(discovery, logger)
	getwayUsecase := biz.NewGetwayUsecase(goodsClient, userClient, logger)
	getwayService := service.NewGetwayService(getwayUsecase)
	httpServer := server.NewHTTPServer(confServer, getwayService, logger)
	grpcServer := server.NewGRPCServer(confServer, getwayService, logger)
	registrar := data.NewRegistrar(naming)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
