apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-log-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-once-pvc
  namespace: k8s-practice
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-many-pvc
  namespace: k8s-practice
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
