# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: log-volume
#   namespace: k8s-practice
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: slow
#   claimRef:
#     name: log-volume-pvc
#     namespace: k8s-practice
#   mountOptions:
#     - hard
#     - nfsvers=4.1
#   nfs:
#     path: /tmp
#     server: 172.17.0.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-log-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: k8s-practice
spec:
  storageClassName: local-log-sc
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
