version: '3'

services:
  # redis:
  #   hostname: redis
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - 6379:6379

  order-svc:
    image: kilii/svc-app-order:0.1.0
    container_name: order.svc
    ports:
      - "8888:8888"
      - "9999:9999"
      
  greet-svc:
    image: kilii/svc-app-greet:0.1.1
    container_name: greet.svc
    ports:
      - "8888:8888"
      - "9999:9999"