version: '3'

services:
  # redis:
  #   hostname: redis
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - 6379:6379

  order-svc:
    image: order:latest
    container_name: order.svc
    ports:
      - "8080:8080"
      - "8888:8888"
      
  greet-svc:
    image: greet:latest
    container_name: greet.svc
    ports:
      - "8080:8080"
      - "8888:8888"