// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-getway/internal/biz"
	"api-getway/internal/conf"
	"api-getway/internal/data"
	"api-getway/internal/server"
	"api-getway/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	getwayRepo := data.NewGetwayRepo(dataData, logger)
	getwayUsecase := biz.NewGetwayUsecase(getwayRepo, logger)
	getwayService := service.NewGetwayService(getwayUsecase)
	httpServer := server.NewHTTPServer(confServer, getwayService, logger)
	grpcServer := server.NewGRPCServer(confServer, getwayService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
