// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-getway/internal/biz"
	"api-getway/internal/client"
	"api-getway/internal/conf"
	"api-getway/internal/server"
	"api-getway/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, naming *conf.Naming, logger log.Logger) (*kratos.App, func(), error) {
	registry := client.NewEtcdClient(naming)
	getwayUsecase := biz.NewGetwayUsecase(registry, logger)
	getwayService := service.NewGetwayService(getwayUsecase)
	httpServer := server.NewHTTPServer(confServer, getwayService, logger)
	grpcServer := server.NewGRPCServer(confServer, getwayService, logger)
	app := newApp(logger, httpServer, grpcServer, registry)
	return app, func() {
	}, nil
}
